apiVersion: v2
name: aws-node-termination-handler
description: A Helm chart for the AWS Node Termination Handler.
type: application
version: 0.21.0
keywords:
  - aws
  - eks
  - ec2
  - node-termination
  - spot
home: https://github.com/aws/aws-node-termination-handler/
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws/aws-node-termination-handler/
